# Generated by Django 2.0.4 on 2018-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('authorID', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
    ]
